name: Build CuteCapture
on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [master]
jobs:
  linux-sfml-2-4:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env
        run: |
          REF_END="${GITHUB_REF#refs/}"
          REF_MID="${REF_END%%/*}"
          if [ "$REF_MID" = "tags" ]; then
            echo "CC_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "CC_VERSION=${{ github.sha }}}" >> $GITHUB_ENV
          fi
      - name: Build and Link
        run: |
          sudo apt-get install -y libusb-1.0.0-dev libsfml-dev
          ./autogen.sh && ./configure && make
          chmod +x Cute3DSCapture
          chmod +x CuteDSCapture
          chmod +x install_udev_rules.sh
      - name: Upload Zip
        uses: actions/upload-artifact@master
        with:
          name: CuteCapture-sfml-2.4.linux.zip
          path: |
            Cute3DSCapture
            CuteDSCapture
            install_udev_rules.sh
            README.md
            LICENSE
            THANKS
  linux-sfml-2-5:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env
        run: |
          REF_END="${GITHUB_REF#refs/}"
          REF_MID="${REF_END%%/*}"
          if [ "$REF_MID" = "tags" ]; then
            echo "CC_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "CC_VERSION=${{ github.sha }}}" >> $GITHUB_ENV
          fi
      - name: Build and Link
        run: |
          sudo apt-get install -y libusb-1.0.0-dev libsfml-dev
          ./autogen.sh && ./configure && make
          chmod +x Cute3DSCapture
          chmod +x CuteDSCapture
          chmod +x install_udev_rules.sh
      - name: Upload Zip
        uses: actions/upload-artifact@master
        with:
          name: CuteCapture-sfml-2.5.linux.zip
          path: |
            Cute3DSCapture
            CuteDSCapture
            install_udev_rules.sh
            README.md
            LICENSE
            THANKS
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set env
        run: |
          REF_END="${GITHUB_REF#refs/}"
          REF_MID="${REF_END%%/*}"
          if [ "$REF_MID" = "tags" ]; then
            echo "CC_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "CC_VERSION=dev-${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Build and Link
        run: |
          # versions: libusb@1.0.23 and sfml@2.5.1 at time of writing
          brew install autoconf automake libtool libusb sfml
          ./autogen.sh && ./configure && make
          ./make_macos_app.sh
      - name: Upload Zip
        uses: actions/upload-artifact@master
        with:
          name: CuteCapture.mac.zip
          path: |
            CuteDSCapture.app
            Cute3DSCapture.app
            README.md
            LICENSE
            THANKS
  release:
    needs: [linux-sfml-2-4, linux-sfml-2-5, macos]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: |
          TAG_MESSAGE=$(git tag -l --format='%(contents)' ${GITHUB_REF#refs/tags/})
          echo $TAG_MESSAGE
